parameters:
    ongr_connections.sync.data_sync_service.class: ONGR\ConnectionsBundle\Pipeline\PipelineStarter
    ongr_connections.sync.storage_manager.mysql_storage_manager.class: ONGR\ConnectionsBundle\Sync\StorageManager\MysqlStorageManager
    ongr_connections.sync.sync_storage.class: ONGR\ConnectionsBundle\Sync\SyncStorage\SyncStorage
    # data sync pipeline event parent classes
    ongr_connections.sync.data_sync.source.class: ONGR\ConnectionsBundle\EventListener\DataSyncSourceEventListener
    ongr_connections.sync.data_sync.consume.class: ONGR\ConnectionsBundle\EventListener\DataSyncConsumeEventListener

services:
    ongr_connections.sync.storage_manager.mysql_storage_manager:
        class: '%ongr_connections.sync.storage_manager.mysql_storage_manager.class%'
        # Arguments are injected in bundle Extension class.

    ongr_connections.sync.sync_storage:
        class: '%ongr_connections.sync.sync_storage.class%'
        # Arguments are injected in bundle Extension class.

    ongr_connections.sync.data_sync_service:
        class: '%ongr_connections.sync.data_sync_service.class%'
        calls:
            - [ setPipelineFactory, [ '@ongr_connections.pipeline_factory' ] ]
